# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/
    environment:
      HUGO_BUILD_DIR: ~/public
    steps:
      - run: apk update && apk add git
      - run: apk add --update nodejs nodejs-npm
      - run: npm install aerobatic-cli -g
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
      - run: |
              htmlproofer $HUGO_BUILD_DIR --allow-hash-href --check-html \
              --empty-alt-ignore --disable-external
      - run: areo deploy -d ~/public
    
# `deploy` step: identical to a `run` step, but uses only one container:
# https://circleci.com/docs/2.0/configuration-reference/#deploy



